### ISSUE TITLE
Asset browser: white-on-white tooltips

### ISSUE THREAD

**Issue by dsalt** [djmonkeyuk/nms-base-builder#101]
Adding
```css
QToolTip {
    background: white;
    color: black;
}
```
to `core.css` is sufficient, but I'm not adding a commit for this as you may want different colours and/or opacity.

(Could be a broken Qt5 config or possibly a broken GTK theme, but tooltips are fine in other Qt5 apps.)
